/*generate*/
package com.nd.sdp.conf.impl;

import androidx.annotation.Keep;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;

@Keep
public class ServiceConfigImpl extends AtomicReference<Map<String, Map<String, Object>>> {
    private final Map<String, Map<String, Object>> pps = new HashMap<>();

    public ServiceConfigImpl() {
        HashMap<String, Object> m = null;
        m = new HashMap<>();
            m.put("UCConfigBaseUrl", "https://uc-gateway.beta.101.com/v1.1/");
            m.put("UCAdminBaseUrl", "https://admin-gateway.beta.101.com/v1.1");
            m.put("UCVORGBaseUrl", "https://ucvorg-beta.101.com/v0.1/");
            m.put("ContentBaseUrl", "https://betacs.101.com/v0.1/");
            m.put("UCH5BaseUrl", "https://uc-h5.beta.101.com/");
            m.put("CSAvatarInstance", "preproduction_content_cscommon");
            m.put("CSSessionUrl", "https://cscommon-beta.101.com/v0.1/");
            m.put("ContentDownBaseUrl", "https://betacs.101.com/v0.1/");
            m.put("UCCloudConfigBaseUrl", "https://uc-configuration2.beta.101.com/v1.1");
            m.put("UCThirdAuth", "https://auth-third-beta.101.com/v0.93/");
            m.put("UCWechatTransfer", "https://auth-third-beta.101.com/");
            m.put("UCSecurityBaseUrl", "https://uc-aq.betas.101.com");
            m.put("CaptchaBaseUrl", "https://uc-captcha.beta.101.com/v0.1/");
            m.put("CSFileInstance", "preproduction_content_uc_gateway");
            m.put("UCNewVersionBaseUrl", "https://uc-gateway.beta.101.com/v1.1/");
            m.put("ProtocolUpdateUrl", "https://uc-gateway.beta.101.com");
            m.put("UCBaseUrl", "https://ucbetapi.101.com/v0.93/");
            m.put("UCSecurityDeviceUrl", "https://uc-security-login-h5-web.beta.101.com/?type=dev&_maf_menu_ids=none");
            m.put("UCOmsSearch", "https://oms-search.beta.101.com/v1.1");
            m.put("UCSecurityRecordUrl", "https://uc-security-login-h5-web.beta.101.com/?type=log&_maf_menu_ids=none");
        pps.put("com.nd.sdp.uc_component", m);
        m = new HashMap<>();
            m.put("domain_maintenance_host", "https://portal-app-config.beta.101.com");
        pps.put("com.nd.smartcan.appfactory.main_component", m);
        m = new HashMap<>();
            m.put("host_url", "https://mypage.beta.101.com/v0.1/");
            m.put("cs_mypage_service_name", "preproduction_content_mypage");
            m.put("cs_uploadlog_service_name", "maflogcollection");
            m.put("maflogcollection_url", "https://log-collector.beta.101.com/v0.1");
            m.put("env", "");
        pps.put("com.nd.social.appsetting", m);
        m = new HashMap<>();
            m.put("QRCODE_BASE_URL", "https://im-qrcode-redirect.beta.101.com/v1.0");
            m.put("QRCODE_SCAN_BASE", "https://im-h5-pages.beta.101.com/qrcode/");
        pps.put("com.nd.social.qr-code", m);
        m = new HashMap<>();
            m.put("examplayer_abilityApiHost", "https://ability-exam-api.beta.101.com/");
            m.put("ecoupon_host", "https://coin-certificate-gateway.beta.101.com");
            m.put("business_course_exam_host", "https://auxo-exam-service.beta.101.com");
            m.put("eappkey_host", "https://elearning-gateway.beta.101.com");
            m.put("elearning2_log", "https://elearning-log.debug.ndaeweb.com");
            m.put("examplayer_markApiHost", "https://elearning-mark-api.beta.101.com/");
            m.put("examplayer_onlineExamHost", "https://elearning-onlineexam-api.beta.101.com");
            m.put("examplayer_answerApiHost", "https://elearning-answer-api.beta.101.com/");
            m.put("eqa_web_host", "https://assist.beta.101.com");
            m.put("examplayer_elearningGatewayHost", "https://elearning-gateway.beta.101.com");
            m.put("eqa_host", "https://assist-gw.beta.101.com");
            m.put("exercise_gateway_host", "https://elearning-course-exercise-gateway.beta.101.com");
            m.put("business_course_attendence_gateway_host", "https://e-attendence-gateway.beta.101.com");
            m.put("elearning_service_host", "https://elearning-service.beta.101.com");
            m.put("erecommend_gateway_host", "https://auxo-recommend-gateway.beta.101.com");
            m.put("WrongBookApiHost", "https://wrong-question-gateway.beta.101.com");
            m.put("ecourse_ndvideo-key", "https://ndvideo-key.beta.101.com");
            m.put("ecourse_note_host", "https://elearning-note-api.beta.101.com");
            m.put("e_rn_tag_host", "https://auxo-tag.beta.101.com");
            m.put("business_course_progress_host", "https://elearning-learning-progress-api.beta.101.com");
            m.put("einteract_host", "https://assist-gw.beta.101.com");
            m.put("eexam_host", "https://auxo-exam-service.beta.101.com");
            m.put("examplayer_wqGatewayHost", "https://wrong-question-gateway.beta.101.com");
            m.put("business_course_exam_new_host", "https://elearning-exam-api.beta.101.com");
            m.put("exercise_api_host", "https://elearning-course-exercise-api.beta.101.com");
            m.put("emylearn_host", "https://auxo-my-study-gateway.beta.101.com");
            m.put("assist_host", "https://assist-gw.beta.101.com");
            m.put("eforcelearn_host", "https://auxo-forcestudy-gateway.beta.101.com");
            m.put("elearning2_base", "https://r.cloud.e.101.com");
            m.put("examplayer_perodicExamApiHost", "https://elearning-periodicexam-api.beta.101.com/");
            m.put("examplayer_abilityGatewayHost", "https://ability-exam-gateway.beta.101.com/");
            m.put("eassessment_host", "https://auxo-exam-center-gateway.beta.101.com");
            m.put("userdata_host", "https://auxo-userdata-service.beta.101.com");
            m.put("ecourse_play_error", "https://elearning-log.beta.101.com/v1/log/play/error");
            m.put("evideo_91open", "https://r.cloud.e.101.com");
            m.put("eqa_gateway_host", "https://assist-gw.beta.101.com");
            m.put("examplayer_exerciseCourseApiHost", "https://elearning-course-exercise-api.beta.101.com");
            m.put("elearning_tenant_api", "https://elearning-tenant-api.beta.101.com");
            m.put("eopencourses_2gateway_host", "https://opencourse2-gateway.beta.101.com");
            m.put("examplayer_pkApiHost", "https://elearning-pk-api.beta.101.com/");
            m.put("eqa_host_mystudy", "https://auxo-my-study-gateway.beta.101.com");
            m.put("business_course_gateway_host", "https://business-course-gateway.beta.101.com");
            m.put("eforcelearn2_host", "https://auxo-forcestudy2-gateway.beta.101.com");
            m.put("examplayer_pkHost", "https://elearning-pk-gateway.beta.101.com/");
            m.put("evideo_host", "https://auxo-gateway.beta.101.com");
            m.put("train2_host", "https://elearning-train-gateway.beta.101.com");
            m.put("ecourse_host", "https://auxo-gateway.beta.101.com");
            m.put("elearning2_gateway", "https://elearning-gateway.beta.101.com");
            m.put("eenroll_voucher_h5_host", "https://elearning-enroll-gateway.beta.101.com");
            m.put("eevaluation_host", "https://assist-gw.beta.101.com");
            m.put("eqa_mystudy_host", "https://auxo-my-study-gateway.beta.101.com");
            m.put("etag_host", "https://elearning-tag-gateway.beta.101.com");
            m.put("business_course_service_host", "https://business-course-service.beta.101.com");
            m.put("eopencourses_host", "https://auxo-open-course-gateway.beta.101.com");
            m.put("examplayer_wqApiHost", "https://wrong-question-api.beta.101.com");
            m.put("admin_host", "https://admin-new.beta.101.com");
            m.put("examplayer_onlineExamGatewayHost", "https://elearning-onlineexam-gateway.beta.101.com");
            m.put("eexam_host_log", "https://elearning-gateway.beta.101.com");
            m.put("examplayer_answerGatewayHost", "https://elearning-answer-gateway.beta.101.com");
            m.put("examplayer_resourceGatewayHost", "https://resource-gateway.beta.101.com");
            m.put("erecommend_host", "https://auxo-recommand-gateway.beta.101.com");
            m.put("eexam_host_resource", "https://resource-gateway.beta.101.com");
            m.put("elearning2_net", "https://api.re.101.com");
            m.put("examplayer_examHost", "https://elearning-exam-api.beta.101.com");
            m.put("erec_course_host", "https://auxo-recommend.beta.101.com");
            m.put("examplayer_perodicExamGateawayHost", "https://elearning-periodicexam-gateway.beta.101.com");
            m.put("train2_api_host", "https://elearning-train-api.beta.101.com");
            m.put("edocument_host", "https://auxo-gateway.beta.101.com");
        pps.put("com.nd.sdp.component.elearning-configs", m);
        m = new HashMap<>();
            m.put("h5Host", "https://pbl-h5-page.beta.101.com");
            m.put("dailyHost", "https://sign-daily-completion.beta.101.com");
            m.put("signOutHost", "https://sign-out.beta.101.com");
            m.put("taskHost", "https://pbl4task.beta.101.com");
            m.put("guardHost", "https://pbl4guard.beta.101.com");
            m.put("pblHost", "https://pbl4personal.beta.101.com");
            m.put("userHost", "https://pbl4user.beta.101.com");
            m.put("envInt", "5");
            m.put("signHost", "https://im-sign.beta.101.com");
            m.put("dailyPage", "https://sign-daily-completion.beta.101.com/?_maf_menu_ids=none#/daily");
            m.put("levelHost", "https://level4culture.beta.101.com");
        pps.put("com.nd.pbl.pblcomponent", m);
        m = new HashMap<>();
            m.put("js_interface_sample_host", "https://js-interface-sample.beta.101.com/");
        pps.put("com.nd.sdp.appfactory.jssdk", m);
        m = new HashMap<>();
            m.put("evideo_91open", "http://r.cloud.e.101.com");
            m.put("evideo_host", "http://auxo-gateway.beta.web.sdp.101.com");
            m.put("resouceKey_host", "https://ndvideo-key.beta.101.com");
            m.put("evideo_log", "http://elearning-log.beta.web.sdp.101.com");
            m.put("resouceKey", "https://ndvideo-key.beta.101.com");
        pps.put("com.nd.hy.android.video.video", m);
        m = new HashMap<>();
            m.put("ContentBaseUrl", "https://betacs.101.com/v0.1/");
            m.put("ContentImageHost", "betacs.101.com");
            m.put("ContentDownBaseUrl", "https://betacs.101.com/v0.1/");
            m.put("ContentGlobalUrl", "https://betacs.101.com/v0.1/");
        pps.put("com.nd.sdp.library.cscom", m);
        m = new HashMap<>();
            m.put("host", "https://userinfo.beta.101.com/v0.1");
            m.put("my_page_url", "https://mypage.beta.web.sdp.101.com/v0.1");
            m.put("cs_service_name", "preproduction_content_userinfo");
            m.put("model_host", "https://model.beta.101.com/v0.1");
        pps.put("com.nd.sdp.component.userinfo-view-single-app", m);
        m = new HashMap<>();
            m.put("EMOTIONMALL_ENVKEY", "https://im-emotion.beta.101.com/v0.3");
            m.put("KEY_CS_SERVER_NAME", "preproduction_content_im_emotion");
        pps.put("com.nd.sdp.component.ui-emotion-panel", m);
        m = new HashMap<>();
            m.put("edocument_host", "http://auxo-gateway.beta.web.sdp.101.com");
        pps.put("com.nd.hy.android.reader", m);
        m = new HashMap<>();
            m.put("shorturl_url", "https://shorturl.beta.101.com/");
            m.put("cs_download_service_name", "fake_share");
        pps.put("com.nd.social.socialShare", m);
        m = new HashMap<>();
            m.put("RBAC_URL", "https://rbac.beta.101.com/v0.1");
            m.put("RBAC_ENV", "preproduction");
            m.put("RBAC_CS_SERVICE_NAME", "preproduction_content_rbac");
        pps.put("com.nd.sdp.component.rbaccmp", m);
        m = new HashMap<>();
            m.put("censor_cs_server_name", "preproduction_content_censor");
            m.put("censor_url", "http://censor.beta.web.sdp.101.com/v0.1");
            m.put("new_censor_url", "https://censor2.beta.101.com/v0.1");
        pps.put("com.nd.sdp.sensitivewordfilter.sensitivewordfilter", m);
        m = new HashMap<>();
            m.put("mypage_url", "https://mypage.beta.101.com/v0.1/");
        pps.put("com.nd.sdp.android.org.server.adapter.orgserveradapter", m);
        m = new HashMap<>();
            m.put("mypage_url", "https://mypage.beta.101.com/v0.1/");
        pps.put("com.nd.social.mypagesdk", m);
        m = new HashMap<>();
            m.put("limit_host", "https://sg-service-access-limit.beta.101.com");
        pps.put("com.nd.edu.component.el-router", m);
        m = new HashMap<>();
            m.put("resource_config_host", "https://resource-config-service.beta.101.com");
        pps.put("com.nd.sdp.component.el-rescard", m);
        m = new HashMap<>();
            m.put("configuration_center_host", "https://config-cfgcenter.beta.101.com");
            m.put("configuration_center_cs_host", "https://betacs.101.com");
            m.put("configuration_center_dir", "high_avl");
            m.put("configuration_center_env", "preproduction");
            m.put("configuration_center_service_name", "preproduction_content_cfgcenter");
        pps.put("com.nd.sdp.component.configure", m);
        m = new HashMap<>();
            m.put("TAG_DIMENSION_GROUP_ID", "114576");
            m.put("TAG_NODE_DIMENSION_ID", "114577");
            m.put("TAG_SERVER_URL", "https://esp-tag.beta.101.com/v1.0");
            m.put("TAG_TENANT_ID", "oms");
            m.put("TAG_USER_DIMENSION_ID", "114578");
        pps.put("com.nd.sdp.component.tag-sdk", m);
        m = new HashMap<>();
            m.put("library_business_host", "https://elearning-library-business-service.beta.101.com");
            m.put("cs_host", "https://betacs.101.com/v0.1/static");
            m.put("library_host", "https://elearning-study-library-gateway.beta.101.com");
        pps.put("com.nd.sdp.component.edu-studycontent", m);
        m = new HashMap<>();
            m.put("smart_link_host", "https://elearning-smart-link.beta.101.com/");
        pps.put("com.nd.sdp.component.el-smartlink", m);
        m = new HashMap<>();
            m.put("um_standby_domain", "https://quickaplus-server-api-cn-zhangjiakou.aliyuncs.com");
            m.put("x-record-api_host", "https://x-record-api.beta.101.com");
            m.put("um_custom_domain", "https://quickaplus-server-api-cn-zhangjiakou.aliyuncs.com");
        pps.put("com.nd.sdp.component.x-app-stat", m);
        m = new HashMap<>();
            m.put("score_gateway_host", "https://score-gateway.beta.101.com");
            m.put("score_main_list", "cmp://com.nd.xst.app-center/delegate?pre_action=2&target_uri=https%3A%2F%2Fscore-webapp.beta.101.com%2Fscore-web%2F101mobile%2Findex.html%3Frole%3D%24%7Bidentity_code%7D%23%2FscoreList");
            m.put("score_h5", "https://score-webapp.beta.101.com");
            m.put("cs_host", "https://x-cloud-web.beta.101.com");
            m.put("url_user_feedback", "https://x-edu-h5.beta.101.com/suggestion/report?id={id}&type={type}&name={name}&uploadChatRecord=1");
            m.put("url_feedback_api", "https://feedback.beta.101.com");
            m.put("cs_rootpath", "/preproduction_content_x_cloud/useravatar");
            m.put("url_user_guide", "https://h5.zxx.edu.cn/guide");
            m.put("cs_servicename", "preproduction_content_x_cloud");
            m.put("mine_config_src", "https://api.ykt.cbern.com.cn/zxx/api_static/data_pre/mine_home_config.json");
            m.put("url_assessment", "https://classroom-assessment.beta.101.com");
        pps.put("com.nd.sdp.component.x-user", m);
        m = new HashMap<>();
            m.put("remark_name_host", "https://remark-name.beta.101.com/v1.0");
        pps.put("com.nd.sdp.component.remark-name-mo", m);
        m = new HashMap<>();
            m.put("x_cloud_assemble_service", "https://x-cloud-web.beta.101.com");
            m.put("social_notice_host", "https://notice.beta.101.com");
            m.put("introduce_url", "https://h5-xue.zxx.edu.cn/introduce?_maf_menu_ids=none");
            m.put("share_icon_url", "https://cdncs.ykt.cbern.com.cn/v0.1/static/x_cloud_web/x_icon/x_icon.png");
            m.put("edu_homework_host", "https://elearning-homework-service.beta.101.com");
            m.put("cdn_cs_static_content_servicename", "preproduction_content_zxx");
            m.put("xcloud_course_tags_static", "preproduction_content_tag_plugin");
            m.put("cdn_cs_static_content_servicename_forThailll", "preproduction_content_staticize");
            m.put("x_im_user_appeal_url", "https://x-edu-h5.beta.101.com/appeal?account_id={account_id}");
            m.put("url_feedback_api", "https://feedback.beta.101.com");
            m.put("introduce_icon_url", "https://bdcs-file-1.ykt.cbern.com.cn/zxx/cover/app_welcome.png");
            m.put("x_cloud_avatar_cdn_host", "https://betacs.101.com/v0.1/static");
            m.put("xcloud_tag_view_static", "preproduction_content_x_cloud");
            m.put("cdn_cs_static_host", "https://ndcs-pre.101.com");
            m.put("x_proxy_host", "https://x-proxy.beta.101.com/proxy");
            m.put("live_activity_gateway_host", "https://x-live-activity-gateway.beta.101.com");
            m.put("edu_admin_public_base_service_host", "https://edu-admin-public-base.beta.101.com");
            m.put("edu_habit_host", "https://habit-cultivate-api.beta.101.com");
            m.put("x_cloud_avatar_servicename", "preproduction_content_x_cloud");
            m.put("x_cloud_address_static_service", "preproduction_content_x_cloud");
        pps.put("com.nd.sdp.component.x-cloud-assemble", m);
        m = new HashMap<>();
            m.put("limit_host", "https://sg-service-access-limit.beta.101.com");
        pps.put("com.nd.sdp.common.flow-control", m);
        m = new HashMap<>();
            m.put("lite_app_service", "https://lite-app-service.beta.101.com");
            m.put("portal_app_server_host", "https://portal-app-config.beta.101.com");
            m.put("JsBridgeAllowedList", "https://portal-web-domain-manage.beta.101.com");
        pps.put("com.nd.smartcan.appfactory.maincomponent.ext-lightapp-hotupdate", m);
        m = new HashMap<>();
            m.put("relationshipUrl", "https://relation-auth-service.beta.101.com");
        pps.put("com.nd.edu.ap.component.parent-child-raship", m);
        m = new HashMap<>();
            m.put("x_user_connect_host", "https://x-user-connect-api.beta.101.com");
            m.put("x_examination_papers_url", "https://h5-test.ykt.eduyun.cn");
            m.put("x_external_client_host", "https://login.system.eduyun.cn");
            m.put("block_exceptions", ".*/app_conf.json,.*config-cfgcenter..*/com.nd.sdp.component%3Ax-cloud-assemble/.*,.*/app_func.json,.*/req_interceptor.*.json,.*/platform_config.json");
            m.put("area_site_tenant_code", "preproduction_content_x_cloud");
            m.put("live_activity_gateway_host", "https://x-live-activity-gateway.beta.101.com");
            m.put("content_recommend_service", "https://x-recommend-service.beta.101.com");
            m.put("edu_admin_public_base_service_host", "https://edu-admin-public-base.beta.101.com");
            m.put("x_edu_h5_host", "https://x-edu-h5.beta.101.com");
            m.put("doc_center_host", "https://doc-center.beta.101.com");
            m.put("x_cs_service_host", "https://betacs.101.com");
            m.put("XCourseHost", "https://x-course.beta.101.com");
            m.put("block_list", "");
            m.put("x_connect_gateway", "https://x-connect-gateway.beta.101.com");
            m.put("training_course_tenant_code", "preproduction_content_x_course");
        pps.put("com.nd.xst.xs-commons", m);
        m = new HashMap<>();
            m.put("ndvideo-key_host", "https://ndvideo-key.beta.101.com");
            m.put("x-cloud-web", "https://x-cloud-web.beta.101.com");
            m.put("ndr_service_name", "preproduction_content_zxx");
        pps.put("com.nd.xst.x-player", m);
        m = new HashMap<>();
            m.put("x_search_auxo_training_url", "https://xue-test.ykt.eduyun.cn/training/${resource_id}");
            m.put("x_cms_h5", "https://x-edu-h5.beta.101.com");
            m.put("x_top", "");
            m.put("x_cloud_host", "https://x-cloud-web.beta.101.com");
            m.put("ndr_special_service_name", "preproduction_content_zxx");
            m.put("x_cloud_cdn", "https://betacs.101.com/v0.1/static/preproduction_content_x_cloud");
            m.put("x_recommend_teacher_studio", "");
            m.put("x_recommend_service", "https://x-recommend-service.beta.101.com");
            m.put("x_follow_host", "https://x-follow-api.beta.101.com");
            m.put("x_course_dynamic_host", "https://pretest-s-file-1.ykt.cbern.com.cn");
            m.put("resource_jump_middle", "https://resource-jump-middle.beta.101.com/jumpTo");
            m.put("cdn_service_name", "/preproduction_content_x_cloud");
            m.put("x_study_host", "https://x-my-study.beta.101.com");
            m.put("x_study_section", "http://betacs.101.com/v0.1/static/preproduction_content_x_cloud/api_static/data/study_extend_section.json");
            m.put("x_follow_inst_studio", "");
            m.put("x_recommend_inst_studio", "");
            m.put("x_bdcs_file", "");
            m.put("search_platform_config_url", "https://api.ykt.cbern.com.cn/zxx/api_static/conf_pre/searchconfig_platform.json");
            m.put("x_special_cs_servicename", "preproduction_content_x_cloud");
            m.put("x_follow_expert_studio", "");
            m.put("x_special_topic_home_host", "https://x-cloud.beta-site.ndaeweb.com");
            m.put("x_proxy_host", "https://x-proxy.beta.101.com/proxy");
            m.put("x_studio_cs_service_name", "preproduction_content_studio");
            m.put("x_search_host", "https://x-search.beta.101.com");
            m.put("x_studio_cs_host", "https://ndcs-pre.101.com");
            m.put("x_study_record_host", "https://x-study-record-api.beta.101.com");
            m.put("x_edu_h5_host", "https://x-edu-h5.beta.101.com");
            m.put("x_tag_channel_host", "https://h5-test.ykt.eduyun.cn/searchTag");
            m.put("x_special_topic_config_tenant", "https://api.ykt.cbern.com.cn/zxx/api_static/conf/librarylist.json");
            m.put("x_course_tab", "https://api.ykt.cbern.com.cn/zxx/api_static/data_pre/course_tabs.json");
            m.put("x_exercise_host", "https://h5-test.ykt.eduyun.cn");
            m.put("x_follow_teacher_studio", "");
            m.put("x_recommend_article", "");
        pps.put("com.nd.xst.study-activity", m);
        m = new HashMap<>();
            m.put("ndr_service_name", "preproduction_content_zxx");
            m.put("recommend_api_host", "");
            m.put("teach_service_name", "/preproduction_content_x_course/s_course");
            m.put("teach_simple_service_name", "teach");
            m.put("bizCourseGateway_host", "https://x-course.beta.ndaeweb.com");
            m.put("cdn_service_name", "/preproduction_content_x_course/s_course");
            m.put("cdn_simple_service_name", "preproduction_content_x_course");
            m.put("area_site_host", "https://ndcs-pre.101.com");
            m.put("teach_simple_service_iosname", "preproduction_content_x_course");
            m.put("cdn_host", "https://ndcs-pre.101.com");
            m.put("train_api_host", "https://e-train-operation-api.beta.101.com");
        pps.put("com.nd.xst.course", m);
        m = new HashMap<>();
            m.put("x_cloud_expert_studio_id3", "f5b1f770068005f5392621f215f78c94863cd1207b22eec25272eb29b6fb7a5d");
            m.put("x_cloud_studio_id3", "412dde35451229039355f9fc1b2f3e4732c55c4376e469b512746bb142bde46f");
            m.put("x_cloud_web_host", "https://x-cloud-web.beta.101.com");
            m.put("resource_stat_host", "https://x-proxy.beta.101.com/proxy/cloud");
            m.put("x_cloud_school_space_id1", "c91a22c5baba76748bc5d4327283b2854066602db5009e61619c9b1b8ed019b8");
            m.put("e_assessment_host", "https://e-assessment-api.beta.101.com");
            m.put("x_edu_h5_host", "https://x-edu-h5.beta.101.com");
            m.put("x_cloud_studio_host", "https://ndcs-pre.101.com/preproduction_content_studio");
            m.put("e_fav_host", "https://e-favorite-api.beta.101.com");
            m.put("x_cloud_studio_id1", "331593d3-af38-456e-bdb8-5263525608f4");
            m.put("x_cloud_studio_id2", "331593d3-af38-456e-bdb8-5263525608f4-teach-studio");
            m.put("x_cloud_follow_host", "https://x-follow-api.beta.101.com");
            m.put("x_cloud_inst_studio_id3", "d61d6964cf93ed2bafcd64806be8aa1b625e862f8b4651d5df7b997220283199");
            m.put("e_assessment_cdn_host", "https://e-assessment-api.beta.101.com");
            m.put("x_cloud_inst_studio_id2", "331593d3-af38-456e-bdb8-5263525608f4-inst-studio");
        pps.put("com.nd.xst.content-interact", m);
        m = new HashMap<>();
            m.put("uc-gateway", "https://uc-gateway.beta.101.com");
            m.put("elIdetitySwitchHost", "https://x-cloud-web.beta.101.com");
            m.put("uc-admin-gateway", "https://admin-gateway.beta.101.com");
            m.put("elearning-openplatform-gateway", "http://elearning-openplatform-gateway.beta.101.com");
        pps.put("com.nd.xst.x-uc-ext", m);
        m = new HashMap<>();
            m.put("examplayer_channelApiHost", "https://auxo-channel-api.beta.101.com");
            m.put("examplayer_localExamCsServiceName", "preproduction_content_local_exam");
            m.put("examplayer_offlineExamGatewayHost", "https://elearning-offline-exam-gateway.beta.101.com");
            m.put("examplayer_localExamCsServiceId", "bbce705d-e2c3-438c-969c-ff953491ffba");
            m.put("examplayer_CsCdnHost", "https://betacs.101.com");
            m.put("examplayer_onlineExamGatewayCdnHost", "https://elearning-onlineexam-gateway.beta.101.com");
            m.put("examplayer_CsCdnPath", "v0.1/static/preproduction_content_staticize");
            m.put("examplayer_answerCsServiceName", "preproduction_content_huayu_cs");
            m.put("examplayer_ExamApiHost", "https://elearning-exam-api.beta.101.com");
            m.put("examplayer_pkApiHost", "http://elearning-pk-api.beta.101.com/");
            m.put("examplayer_certificateApiHost", "http://auxo-certificate-gateway.beta.web.sdp.101.com");
            m.put("examplayer_markApiHost", "http://elearning-mark-api.beta.101.com");
            m.put("examplayer_onlineExamHost", "https://elearning-onlineexam-api.beta.101.com");
            m.put("examplayer_LocalExamApiHost", "https://local-exam.beta.101.com");
            m.put("examplayer_answerApiHost", "https://elearning-answer-api.beta.101.com");
            m.put("examplayer_pkHost", "http://elearning-pk-gateway.beta.101.com/");
            m.put("examplayer_questionnaireGatewayHost", "https://questionnaire-gateway.beta.101.com/");
            m.put("examplayer_onlineExamGatewayHost", "https://elearning-onlineexam-gateway.beta.101.com");
            m.put("examplayer_answerGatewayHost", "https://elearning-answer-gateway.beta.101.com");
            m.put("examplayer_CsHost", "https://betacs.101.com");
            m.put("examplayer_resourceGatewayHost", "http://resource-gateway.beta.web.sdp.101.com");
            m.put("examplayer_questionnaireServiceHost", "https://questionnaire-service.beta.101.com");
            m.put("examplayer_businesscourseGatewayHost", "http://business-course-gateway.beta.101.com");
            m.put("examplayer_perodicExamApiHost", "http://elearning-periodicexam-api.beta.101.com/");
            m.put("examplayer_perodicExamGateawayHost", "http://elearning-periodicexam-gateway.beta.101.com");
            m.put("examplayer_offlineExamApiHost", "https://elearning-offline-exam-api.beta.101.com");
            m.put("examplayer_attendenceGatewayHost", "https://e-attendence-gateway.beta.101.com");
        pps.put("com.nd.sdp.component.elearning-exam-player", m);
        m = new HashMap<>();
            m.put("VERSION", "1.9.2");
            m.put("HOST", "https://betacs.101.com/v0.1/static/preproduction_content_esp_dvpt");
        pps.put("com.nd.sdp.courseware.courseware-exercise-weaver", m);
        m = new HashMap<>();
            m.put("SERVICE_NAME", "preproduction_content_esp_dvpt");
            m.put("EXERCISE_VERSION", "v2.0");
            m.put("EXERCISE_HOST", "https://esp-exercises-gateway.betas.101.com");
            m.put("SESSION_HOST", "http://esp-developer-service.beta.web.sdp.101.com");
            m.put("SCOPE", "1");
            m.put("REMOTE_PATH", "answer_attachments");
            m.put("SESSION_VERSION", "v0.1");
            m.put("VERSION", "1.9.2");
            m.put("HOST", "https://betacs.101.com/v0.1/static/preproduction_content_esp_dvpt");
        pps.put("com.nd.sdp.courseware.courseware-exercise-master", m);
        m = new HashMap<>();
            m.put("public_key_host", "https://transport-crypto-api.beta.101.com");
        pps.put("com.nd.sdp.component.security-transporter", m);
        m = new HashMap<>();
            m.put("eassessment_host", "https://auxo-exam-center-gateway.beta.101.com");
            m.put("ecoupon_host", "https://coin-certificate-gateway.beta.101.com");
            m.put("evideo_91open", "https://r.cloud.e.101.com");
            m.put("eappkey_host", "https://elearning-gateway.beta.101.com");
            m.put("elearning2_log", "https://elearning-log.beta.101.com");
            m.put("eqa_host_mystudy", "https://auxo-my-study-gateway.beta.101.com");
            m.put("eforcelearn2_host", "https://auxo-forcestudy2-gateway.beta.101.com");
            m.put("community_gateway", "https://learning-community-gateway.beta.101.com");
            m.put("evideo_host", "https://auxo-gateway.beta.101.com");
            m.put("train2_host", "https://elearning-train-gateway.beta.101.com");
            m.put("ecourse_host", "https://auxo-gateway.beta.101.com");
            m.put("elearning2_gateway", "https://elearning-gateway.beta.101.com");
            m.put("eqa_host", "https://auxo-qa-gateway.beta.101.com");
            m.put("eevaluation_host", "https://auxo-appraise-gateway.beta.101.com");
            m.put("echannel_host", "https://r.mobile.p.101.com");
            m.put("erecommend_gateway_host", "https://auxo-recommend-gateway.beta.101.com");
            m.put("etag_host", "https://elearning-tag-gateway.beta.101.com");
            m.put("eopencourses_host", "https://auxo-open-course-gateway.beta.101.com");
            m.put("eexam_host_log", "https://elearning-gateway.beta.101.com");
            m.put("einteract_host", "https://auxo-share-gateway.beta.101.com");
            m.put("eexam_host", "https://auxo-exam-service.beta.101.com");
            m.put("erecommend_host", "https://auxo-recommand-gateway.beta.101.com");
            m.put("eexam_host_resource", "https://resource-gateway.beta.101.com");
            m.put("emylearn_host", "https://auxo-my-study-gateway.beta.101.com");
            m.put("eforcelearn_host", "https://auxo-forcestudy-gateway.beta.101.com");
            m.put("elearning2_net", "https://api.re.101.com");
            m.put("elearning2_base", "https://r.cloud.e.101.com");
            m.put("edocument_host", "https://auxo-gateway.beta.101.com");
        pps.put("com.nd.hy.elearning", m);
        m = new HashMap<>();
            m.put("area_cs_service_host_new", "https://ndcs-pre.101.com");
            m.put("echannel_new_host", "https://elearning-channel-gateway.beta.101.com");
            m.put("area_cs_service_host", "https://betacs.101.com/v0.1/static");
            m.put("cs_service_name", "preproduction_content_staticize");
            m.put("erecommend_host", "https://auxo-recommend-gateway.beta.101.com");
            m.put("resmall_host", "https://elearning-market-gateway.beta.101.com");
            m.put("econtent_host", "https://elearning-library-gateway.beta.101.com");
            m.put("x_proxy_host", "https://x-proxy.beta.101.com");
            m.put("limit_host", "https://sg-service-access-limit.beta.101.com");
            m.put("cdn_echannel_new_host", "https://betacs.101.com/v0.1/static");
            m.put("x_area_edu_h5_host", "https://x-area-edu-h5.beta.101.com");
            m.put("x_connect_gateway", "https://x-connect-gateway.beta.101.com");
            m.put("preview_host", "https://preview-gateway.beta.101.com");
            m.put("area_cs_service_name", "preproduction_content_x_cloud");
            m.put("auth_h5_host", "https://login.system.eduyun.cn");
        pps.put("com.nd.sdp.component.ele-channel", m);
        m = new HashMap<>();
            m.put("eforcelearn2_host", "https://auxo-forcestudy2-gateway.beta.web.sdp.101.com");
            m.put("eoms_host", "https://eoms-api.beta.101.com");
            m.put("h5_host", "https://study-task-webapp.beta.101.com");
            m.put("elemytask_host", "https://elearning-task-api.beta.101.com");
        pps.put("com.nd.sdp.component.ele-compulsory-learning-business", m);
        m = new HashMap<>();
            m.put("task_host", "https://elearning-task-api.beta.101.com/");
            m.put("emylearn_host", "https://auxo-my-study-gateway.beta.101.com");
            m.put("emylearnservice_host", "https://auxo-my-study-service.beta.101.com");
            m.put("emylearn_live_gateway_host", "https://elearning-gateway.beta.101.com");
        pps.put("com.nd.sdp.component.ele-my-study", m);
        m = new HashMap<>();
            m.put("service_url", "https://data-collect-service.beta.101.com/v1/data_collect/{APP_ID}");
        pps.put("com.nd.xst.mob-stat-sa", m);
        m = new HashMap<>();
            m.put("edu_public_basic_service", "https://edu-admin-public-base.beta.101.com");
            m.put("x_dict_config_url", "https://bdcs-file-1.ykt.cbern.com.cn/bdxcloud/configs");
            m.put("x_user_profile_service", "https://x-user-profile.beta.101.com");
            m.put("x_bdcs_file_host", "https://bdcs-file-1.ykt.cbern.com.cn");
        pps.put("com.nd.sdp.component.e-user-info", m);
        m = new HashMap<>();
            m.put("x_study_record_service", "https://x-study-record-api.beta.101.com");
            m.put("e_train_gateway", "https://elearning-train-gateway.beta.101.com");
            m.put("x_s_file_host", "https://ndcs-pre.101.com");
            m.put("teacher_community_cs_service_name", "preproduction_content_staticize");
            m.put("x_study_h5_url", "https://x-edu-h5.beta.101.com");
            m.put("teacher_community_service", "https://teacher-community-service.beta.101.com");
            m.put("x_user_profile_service", "https://x-user-profile.beta.101.com");
            m.put("e_train_service", "https://elearning-train-api.beta.101.com");
            m.put("x_bdcs_file_host", "https://bdcs-file-1.ykt.cbern.com.cn");
        pps.put("com.nd.sdp.component.e-teacher-community", m);
        m = new HashMap<>();
            m.put("MD_ENV", "preproduction");
        pps.put("com.nd.sdp.component.model-app", m);
        m = new HashMap<>();
            m.put("eenroll_statistic", "https://data-statistics-new.beta.101.com");
            m.put("eenroll_gateway", "http://elearning-enroll-gateway.beta.web.sdp.101.com");
            m.put("eenroll_api", "http://elearning-enroll-api.beta.web.sdp.101.com");
        pps.put("com.nd.sdp.component.elearn-enroll", m);
        m = new HashMap<>();
            m.put("activity_host", "https://x-class-hour-activity.beta.101.com");
            m.put("ndvideo-key_host", "https://ndvideo-key.beta.101.com");
            m.put("userdata-service_host", "https://auxo-userdata-service.beta.101.com");
            m.put("x_edu_h5_host", "https://x-edu-h5.beta.101.com");
            m.put("search_host", "https://x-search.beta.101.com");
            m.put("cdn_service_name", "preproduction_content_x_course/s_course");
            m.put("cdn_simple_service_name", "preproduction_content_zxx");
            m.put("activity-frame-web_host", "https://ele-activity-frame-web.betas.101.com");
            m.put("cdn_simple_host", "https://ndcs-pre.101.com");
            m.put("cdn_host", "https://ndcs-pre.101.com/preproduction_content_x_course/s_course");
            m.put("share_icon_host", "https://ndcs-pre.101.com/preproduction_content_x_course/share/e_course_icon_share_doc.png");
        pps.put("com.nd.sdp.component.xcloud-class-activity", m);

        set(pps);
    }

}